"use client";
// ============================================
// Update lifecycle mutations — approve / reject / force-cancel (S4)
//
// retry:false on ALL three: these are state transitions (approve/force-cancel
// also money-moving). A blind retry after a lost-but-committed response would
// hit the backend a second time — for approve/force-cancel the Idempotency-Key
// makes that a safe replay, but for reject a second attempt would 400 (no
// longer PENDING). So we never auto-retry; the backend guard is the authority
// and the user re-triggers deliberately. NO optimistic updates on any of them
// (money-moving must reflect only server-confirmed state — plan success bar).
//
// Every variable set carries the full invalidation context (id + phaseId +
// projectId) so onSuccess refetches exactly:
//   1. the phase's update lists (status changed)      → PHASE_UPDATES_QUERY_KEY/phaseId
//   2. the update detail (status/reviewer changed)     → updateQueryKey(id)
//   3. the project detail (overallProgress recalc'd)   → projectQueryKey(projectId)
// The Idempotency-Key is generated by the caller's holder and passed in — never
// generated here (per-call generation would break stability across retries).
// ============================================
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  approveUpdate,
  forceCancelUpdate,
  rejectUpdate,
  type UpdateActionResult,
} from "@/lib/api/updates-client";
import { projectQueryKey } from "./use-project";
import { PHASE_UPDATES_QUERY_KEY } from "./use-phase-updates";
import { updateQueryKey } from "./use-update";

/** Context every review action needs to invalidate the right caches. */
interface ReviewContext {
  id: string;
  phaseId: string;
  projectId: string;
}
interface ApproveVars extends ReviewContext {
  idempotencyKey: string;
}
interface RejectVars extends ReviewContext {
  reason: string;
}
interface ForceCancelVars extends ReviewContext {
  reason: string;
  idempotencyKey: string;
}

/** Shared invalidation: phase lists + the update detail + the project detail. */
function useInvalidateReview() {
  const queryClient = useQueryClient();
  return ({ id, phaseId, projectId }: ReviewContext) => {
    queryClient.invalidateQueries({
      queryKey: [...PHASE_UPDATES_QUERY_KEY, phaseId],
    });
    queryClient.invalidateQueries({ queryKey: updateQueryKey(id) });
    queryClient.invalidateQueries({ queryKey: projectQueryKey(projectId) });
  };
}

/** POST /updates/:id/approve — PENDING → APPROVED (idempotent). */
export function useApproveUpdate() {
  const invalidate = useInvalidateReview();
  return useMutation<UpdateActionResult, unknown, ApproveVars>({
    mutationFn: ({ id, idempotencyKey }) => approveUpdate(id, idempotencyKey),
    retry: false,
    onSuccess: (_data, vars) => invalidate(vars),
  });
}

/** POST /updates/:id/reject — PENDING → REJECTED. */
export function useRejectUpdate() {
  const invalidate = useInvalidateReview();
  return useMutation<UpdateActionResult, unknown, RejectVars>({
    mutationFn: ({ id, reason }) => rejectUpdate(id, { reason }),
    retry: false,
    onSuccess: (_data, vars) => invalidate(vars),
  });
}

/** POST /updates/:id/force-cancel — APPROVED → FORCE_CANCELLED (idempotent). */
export function useForceCancelUpdate() {
  const invalidate = useInvalidateReview();
  return useMutation<UpdateActionResult, unknown, ForceCancelVars>({
    mutationFn: ({ id, reason, idempotencyKey }) =>
      forceCancelUpdate(id, { reason }, idempotencyKey),
    retry: false,
    onSuccess: (_data, vars) => invalidate(vars),
  });
}
