// ============================================
// 🏗️ Construction SaaS — Permission System
// resource.action format
// ============================================

export const PERMISSIONS = {
  // Company
  COMPANY_VIEW: 'company.view',
  COMPANY_EDIT: 'company.edit',
  COMPANY_MANAGE_SETTINGS: 'company.manage_settings',
  COMPANY_MANAGE_USERS: 'company.manage_users',
  COMPANY_MANAGE_BILLING: 'company.manage_billing',

  // Projects
  PROJECTS_VIEW: 'projects.view',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_EDIT: 'projects.edit',
  PROJECTS_DELETE: 'projects.delete',
  PROJECTS_ASSIGN_MEMBERS: 'projects.assign_members',
  PROJECTS_VIEW_ANALYTICS: 'projects.view_analytics',

  // Phases
  PHASES_VIEW: 'phases.view',
  PHASES_CREATE: 'phases.create',
  PHASES_EDIT: 'phases.edit',
  PHASES_DELETE: 'phases.delete',

  // Updates
  UPDATES_VIEW_OWN: 'updates.view_own',
  UPDATES_VIEW_ALL: 'updates.view_all',
  UPDATES_CREATE: 'updates.create',
  UPDATES_EDIT_DRAFT: 'updates.edit_draft',
  UPDATES_SUBMIT: 'updates.submit',
  UPDATES_APPROVE: 'updates.approve',
  UPDATES_REJECT: 'updates.reject',
  UPDATES_FORCE_CANCEL: 'updates.force_cancel',
  UPDATES_EDIT_APPROVED: 'updates.edit_approved',

  // Payments
  PAYMENTS_VIEW_SUMMARY: 'payments.view_summary',
  PAYMENTS_VIEW_DETAILED: 'payments.view_detailed',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_EDIT: 'payments.edit',

  // Media
  MEDIA_VIEW: 'media.view',
  MEDIA_UPLOAD: 'media.upload',
  MEDIA_DELETE: 'media.delete',

  // Comments
  COMMENTS_VIEW: 'comments.view',
  COMMENTS_CREATE: 'comments.create',
  COMMENTS_CREATE_REVIEW_REQUEST: 'comments.create_review_request',
  COMMENTS_CREATE_CHANGE_REQUEST: 'comments.create_change_request',

  // Chat
  CHAT_VIEW: 'chat.view',
  CHAT_SEND: 'chat.send',
  CHAT_CREATE_ROOM: 'chat.create_room',

  // SubContractors
  SUB_CONTRACTORS_VIEW: 'sub_contractors.view',
  SUB_CONTRACTORS_CREATE: 'sub_contractors.create',
  SUB_CONTRACTORS_EDIT: 'sub_contractors.edit',
  SUB_CONTRACTORS_ASSIGN: 'sub_contractors.assign',

  // Audit Log
  AUDIT_LOG_VIEW: 'audit_log.view',

  // Analytics
  ANALYTICS_VIEW_ALL: 'analytics.view_all',
  ANALYTICS_VIEW_FINANCIAL: 'analytics.view_financial',
  ANALYTICS_VIEW_PERFORMANCE: 'analytics.view_performance',

  // Users
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DEACTIVATE: 'users.deactivate',
  USERS_REMOTE_WIPE: 'users.remote_wipe',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// --- Default permissions per role ---
import { UserRole } from './enums';

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: ALL_PERMISSIONS,

  [UserRole.PROJECT_MANAGER]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_ASSIGN_MEMBERS,
    PERMISSIONS.PROJECTS_VIEW_ANALYTICS,
    PERMISSIONS.PHASES_VIEW,
    PERMISSIONS.PHASES_CREATE,
    PERMISSIONS.PHASES_EDIT,
    PERMISSIONS.PHASES_DELETE,
    PERMISSIONS.UPDATES_VIEW_ALL,
    PERMISSIONS.UPDATES_CREATE,
    PERMISSIONS.UPDATES_EDIT_DRAFT,
    PERMISSIONS.UPDATES_SUBMIT,
    PERMISSIONS.UPDATES_APPROVE,
    PERMISSIONS.UPDATES_REJECT,
    PERMISSIONS.UPDATES_EDIT_APPROVED,
    PERMISSIONS.PAYMENTS_VIEW_DETAILED,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.COMMENTS_VIEW,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_SEND,
    PERMISSIONS.CHAT_CREATE_ROOM,
    PERMISSIONS.SUB_CONTRACTORS_VIEW,
    PERMISSIONS.SUB_CONTRACTORS_CREATE,
    PERMISSIONS.SUB_CONTRACTORS_EDIT,
    PERMISSIONS.SUB_CONTRACTORS_ASSIGN,
    PERMISSIONS.ANALYTICS_VIEW_ALL,
    PERMISSIONS.USERS_VIEW,
  ],

  [UserRole.SITE_ENGINEER]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PHASES_VIEW,
    PERMISSIONS.UPDATES_VIEW_OWN,
    PERMISSIONS.UPDATES_CREATE,
    PERMISSIONS.UPDATES_EDIT_DRAFT,
    PERMISSIONS.UPDATES_SUBMIT,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.COMMENTS_VIEW,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_SEND,
    PERMISSIONS.SUB_CONTRACTORS_VIEW,
  ],

  [UserRole.SUPERVISOR]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PHASES_VIEW,
    PERMISSIONS.UPDATES_VIEW_OWN,
    PERMISSIONS.UPDATES_CREATE,
    PERMISSIONS.UPDATES_EDIT_DRAFT,
    PERMISSIONS.UPDATES_SUBMIT,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.COMMENTS_VIEW,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_SEND,
  ],

  [UserRole.ACCOUNTANT]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PHASES_VIEW,
    PERMISSIONS.UPDATES_VIEW_OWN,
    PERMISSIONS.UPDATES_CREATE,
    PERMISSIONS.UPDATES_EDIT_DRAFT,
    PERMISSIONS.UPDATES_SUBMIT,
    PERMISSIONS.PAYMENTS_VIEW_DETAILED,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.COMMENTS_VIEW,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_SEND,
    PERMISSIONS.ANALYTICS_VIEW_FINANCIAL,
  ],

  [UserRole.WORKER]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PHASES_VIEW,
    PERMISSIONS.UPDATES_VIEW_OWN,
    PERMISSIONS.UPDATES_CREATE,
    PERMISSIONS.UPDATES_EDIT_DRAFT,
    PERMISSIONS.UPDATES_SUBMIT,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
  ],

  [UserRole.CLIENT]: [
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PHASES_VIEW,
    PERMISSIONS.UPDATES_VIEW_ALL,
    PERMISSIONS.PAYMENTS_VIEW_DETAILED,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.COMMENTS_VIEW,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.COMMENTS_CREATE_REVIEW_REQUEST,
    PERMISSIONS.COMMENTS_CREATE_CHANGE_REQUEST,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_SEND,
    PERMISSIONS.CHAT_CREATE_ROOM,
  ],
};
