// ============================================
// 📸 Media DTOs
//
// Trust boundary (skill 05): the client owns NOTHING that ends up in the
// storage path or in the DB metadata that drives auth decisions.
//   - `path`     is generated by the server and echoed back; the client
//                must hand the same path back when registering.
//   - `fileSize` and `mimeType` are NOT accepted from the client anymore.
//                They are re-derived from the file's magic bytes by
//                MediaSecurityService.verifyUploadedFile().
// ============================================
import {
  IsString,
  IsOptional,
  IsEnum,
  IsInt,
  IsNotEmpty,
  MaxLength,
  MinLength,
  Min,
  Matches,
} from 'class-validator';
import { MediaType } from '@prisma/client';

/**
 * POST /api/v1/media/upload-url body
 * Returns a signed upload URL + the storage path the client must hand
 * back when registering. The MediaType determines bucket + size policy.
 */
export class CreateUploadUrlDto {
  @IsEnum(MediaType, { message: 'نوع الوسائط غير صالح' })
  type: MediaType;
}

/**
 * POST /api/v1/updates/:uid/media body
 * The `path` MUST be the one returned by /media/upload-url. The service
 * verifies its prefix (companyId scoping) and re-derives mime + size from
 * the uploaded bytes — the client never sets those.
 */
export class CreateMediaDto {
  // The Supabase Storage object path returned by /media/upload-url.
  // Format: `{companyId}/{userId}/{uuid}.{ext}` — server-generated.
  @IsString({ message: 'مسار الملف مطلوب' })
  @IsNotEmpty({ message: 'مسار الملف مطلوب' })
  @MaxLength(500, { message: 'مسار الملف يتجاوز الحد المسموح' })
  // Defense-in-depth path shape check: lowercase hex/uuid + UUID-like
  // segments + dot-extension. Reject any clever escape attempt at parse time.
  @Matches(/^[a-f0-9-]+\/[a-f0-9-]+\/[A-Za-z0-9._-]+$/, {
    message: 'مسار الملف غير صالح',
  })
  path: string;

  @IsEnum(MediaType, { message: 'نوع الوسائط غير صالح' })
  type: MediaType;

  @IsOptional()
  @IsString()
  @MaxLength(300)
  caption?: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  order?: number;
}

export class ReorderMediaDto {
  @IsInt()
  @Min(0)
  order: number;
}

/**
 * DELETE /api/v1/media/:id body.
 * Reason required for audit defensibility.
 */
export class DeleteMediaDto {
  @IsString({ message: 'سبب الحذف مطلوب' })
  @IsNotEmpty({ message: 'سبب الحذف مطلوب' })
  @MinLength(20, { message: 'سبب الحذف يجب أن يكون 20 حرف على الأقل' })
  @MaxLength(2000)
  reason: string;
}
